name: Commit

on:
    workflow_run:
        workflows: [Node]
        types:
            - completed

jobs:
    prepare:
        uses: ./.github/workflows/node.yml

    commit:
        needs: prepare
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v3.1.0
            - uses: actions/download-artifact@v3.0.1
              id: download
              with:
                  name: .-node-18-dist
                  path: ./dist

            - run: |
                  git add .
                  git config --global user.name 'Optimus Primeagen'
                  git config --global user.email 'the.primeagen@gmail.com'
                  git commit -m "Auto Build"
                  git push
