name: Node

on:
    workflow_dispatch:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18]
        steps:
            - uses: actions/checkout@v3.1.0
            - uses: pnpm/action-setup@v2.2.4
              with:
                  version: 7.13.4
                  run_install: |
                      - recursive: true
                        args: [
                          --child-concurrency=9999,
                          --link-workspace-packages=true,
                          --lockfile-only,
                          --network-concurrency=9999,
                          --prefer-frozen-lockfile=false,
                          --shamefully-hoist=false,
                          --shared-workspace-lockfile=true,
                          --strict-peer-dependencies=false,
                          --unsafe-perm=true
                        ]

            - uses: actions/setup-node@v3.5.1
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./pnpm-lock.yaml
            - run: pnpm install
              working-directory: .

            - run: pnpm run test
              working-directory: .
